### ISSUE TITLE
Windows cannot find Optoinalfeatures.exe

### ISSUE THREAD

**Issue by ExaFlop1** [shortcircuit-design/Jims-Toolbox#1]
Behind Menu button under Optional Windows features returns an error - "Windows cannot find Optoinalfeatures.exe. Make sure..."
But the file C:\Windows\System32\OptionalFeatures.exe exists.

**Comment by shortcircuit-design** [comment]
Thank you for your info, indeed there was a strange bug that gives an error and then opens the Optionalfeatures.exe file. I have changed the method to call the file and there is no more error. This will be as corrected in the next release.
